[features]
seeds = false
[programs.localnet]
tic_tac_toe = "DLBUzNyHxH8Yqn6Jdm15wKchLUwvRaQtT5WoaFQxEsWp"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/mrak/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
